fail_fast: true
repos:
- repo: https://github.com/prettier/prettier
  rev: master
  hooks:
  - id: prettier
    files: \.(css|js|md|markdown|json)
    exclude: ^static/tipuesearch/
- repo: https://github.com/python/black    
  rev: master
  hooks:
  - id: black  
