# Copyright (C) 2017, 2018 Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

language: python
dist: xenial

python:
- '3.7'

env:
- TEST_CMD="pelican content/ -o output/"
- TEST_CMD="pelican content/ -o output/ -s ./publishconf.py"

cache:
  pip

install:
- pip install -r requirements.txt

before_script:
- cd documentation
- make themes-sync
- make plugins-sync

script:
- $TEST_CMD
- w3c_validator $(find output/ -name '*.html' -type f)
