# Copyright (C) 2017, 2018 Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

language: python
dist: xenial

python:
- '3.7'

addons:
 apt:
  packages:
    - openjdk-8-jre  # install Java8 as required by vnu.jar

cache:
- pip
- yarn
- directories:
  - $HOME/.cache/pre-commit

install:
- pip install -r requirements.txt
- pip install -U Online-W3C-Validator
- pip install -U html5validator
- pip install -U pre-commit
- yarn global add yaspeller

before_script:
- cd documentation
- make plugins-sync

script:
- pre-commit run --all-files
- yaspeller --only-errors content/ *.md
- make publish
- w3c_validator $(find output/ -name '*.html' -type f)
- html5validator --root output/
